Júpiter Store/Júpiter Store/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Júpiter_Store.Models;
using Júpiter_Store.ViewModels;
using Microsoft.AspNet.Identity;

namespace Júpiter_Store.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly string _userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
        private Cart ActiveCart
        {
            get
            {
                return _context.Users
                    .Include(u => u.Carts.Select(c => c.Products.Select(p => p.Product)))
                    .Single(u => u.Id == _userId)
                    ?.Carts.SingleOrDefault(c => c.IsActive);
            }
        }

        public CartController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        


        // GET: Cart
        public ActionResult Index()
        {
            return View(new CartViewModel(ActiveCart));
        }

        // GET: Cart/CheckOut
        public ActionResult Checkout()
        {
            if (!ActiveCart.Products.Any())
            {
                return HttpNotFound();
            }

            return View(new CheckoutViewModel(ActiveCart));
        }
    }
}

Júpiter Store/Júpiter Store/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Júpiter_Store.Models;
using System.Data.Entity;
using System.Net;
using System.Web.Http;
using System.Web.Http.Results;

namespace Júpiter_Store.Controllers
{
    [System.Web.Mvc.Authorize(Roles = RoleName.Manager)]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }



        // GET: Products
        [System.Web.Mvc.AllowAnonymous]
        public ActionResult Index()
        {
            var products = _context.Products.ToList();
            products.Reverse();

            return View(products);
        }

        // GET: Products/New
        public ActionResult New()
        {
            var product = new Product();

            return View("ProcuctForm", product);
        }

        // GET: Products/Edit
        public ActionResult Edit(int id)
        {
            var product = _context.Products.SingleOrDefault(p => p.Id == id);

            if (product == null)
                return HttpNotFound();

            return View("ProcuctForm", product);
        }

        // POST: Products/Save
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Product product, HttpPostedFileBase imageFile)
        {
            if (!ModelState.IsValid)
                return View("ProcuctForm", product);

            // New Product
            if (product.Id == 0)
            {
                product.DateAdded = DateTime.Now;

                var newProduct = _context.Products.Add(product);

                if (imageFile != null)
                {
                    newProduct.ImagePath = GetProductImagePath(newProduct, imageFile);

                    imageFile.SaveAs(Server.MapPath(newProduct.ImagePath));
                }

                _context.SaveChanges();

                return Redirect("Index");
            }

            // Edit Product
            if (imageFile != null)
            {
                product.ImagePath = GetProductImagePath(product, imageFile);

                imageFile.SaveAs(Server.MapPath(product.ImagePath));
            }

            var productInDb = _context.Products.Single(p => p.Id == product.Id);

            productInDb.Name = product.Name;
            productInDb.Description = product.Description;
            productInDb.ImagePath = product.ImagePath ?? productInDb.ImagePath;
            productInDb.NumberInStock = product.NumberInStock;
            productInDb.Price = product.Price;

            _context.SaveChanges();

            return Redirect("Index");
        }

        // POST: Products/Delete/1
        public ActionResult Delete(int id)
        {
            var product = _context.Products.Include(p => p.CartsBelonging).SingleOrDefault(p => p.Id == id);

            if (product == null)
                return HttpNotFound();


            if (product.CartsBelonging.Any())
                throw new HttpResponseException(HttpStatusCode.Conflict);


            if (System.IO.File.Exists(Server.MapPath(product.ImagePath)))
            {
                var path = Server.MapPath(product.ImagePath);
                System.IO.File.Delete(path);
            }

            _context.Products.Remove(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        // Helpers

        public string GetProductImagePath(Product product, HttpPostedFileBase imageFile)
        {
            return Path.Combine(@"~\Public\Images\Products", product.Name.Replace(" ", "_") + "_" + product.DateAdded.ToString("yyyyMMddHHmmss") + Path.GetExtension(imageFile.FileName));
        }

    }
}

Júpiter Store/Júpiter Store/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Júpiter_Store.Models;
using Júpiter_Store.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace Júpiter_Store.Controllers
{
    //[Authorize(Roles = RoleName.Admin)]
    public class UserManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly List<RoleViewModel> _roles;

        public UserManagerController()
        {
            _context = new ApplicationDbContext();
            _roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_context));
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_context));

            _roles = _roleManager.Roles
                .Select(r => new RoleViewModel
                {
                    Id = r.Id,
                    Name = r.Name
                })
                .ToList();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }



        // GET: UserManager
        public ActionResult Index()
        {
            var users = _context.Users
                .ToList()
                .Select(u => new UserManagerViewModel()
                {
                    Id = u.Id,
                    Email = u.Email,
                    UserRoles = GetRolesByUserId(u.Id)

                });

            return View(users);
        }

        // GET: UserManager/Edit
        public ActionResult Edit(string userId)
        {
            var user = _context.Users
                .SingleOrDefault(u => u.Id == userId);

            if (user == null)
                return HttpNotFound();

            
            var userManagerViewModel = new UserManagerViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserRoleIds = GetRolesByUserId(user.Id).Select(r => r.Id).ToList(),
                Roles = _roles
            };

            return View("UserManagerForm", userManagerViewModel);
        }

        // POST: UserManager/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(UserManagerViewModel newUserData)
        {
            if (!ModelState.IsValid)
                return View("UserManagerForm", newUserData);


            var applicationUser = _userManager.FindById(newUserData.Id);

            if (applicationUser == null)
                return View("UserManagerForm", newUserData);


            _userManager.RemoveFromRoles(applicationUser.Id, _userManager.GetRoles(applicationUser.Id).ToArray());

            if (newUserData.UserRoleIds != null)
            {
                var userRoleNames = newUserData.UserRoleIds
                    .Select(r => _roleManager.FindById(r).Name)
                    .ToArray();

                foreach (var roleName in userRoleNames)
                {
                    if (!_roleManager.RoleExists(roleName))
                        return View("UserManagerForm", newUserData);
                }

                _userManager.AddToRoles(applicationUser.Id, userRoleNames);
            }

            _userManager.Update(applicationUser);


            var currentApplicationUser = _userManager.FindById(User.Identity.GetUserId());
            var authenticationManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            authenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
            var identity = _userManager.CreateIdentity(currentApplicationUser, DefaultAuthenticationTypes.ApplicationCookie);
            authenticationManager.SignIn(new AuthenticationProperties { IsPersistent = false }, identity);

            return RedirectToAction("Index");
        }



        // Helpers

        private List<RoleViewModel> GetRolesByUserId(string userId)
        {
            return _userManager.GetRoles(userId)
                .Select(r => new RoleViewModel
                {
                    Id = _roleManager.FindByName(r).Id,
                    Name = r
                })
                .ToList();
        }
    }
}

Júpiter Store/Júpiter Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Jupiter Store</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e1320a">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#e1320a">

    <!-- <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->

</head>
<body>
    <header>
        @Html.Partial("_Navbar")
    </header>

    <main class="container">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jupiter Store</p>
        </footer>
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Júpiter Store/Júpiter Store/Views/Shared/_Navbar.cshtml
@using Júpiter_Store.Models
<nav class="navbar navbar-expand-md fixed-top navbar-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">
            <img src="/Content/img/jupiter-logo-32.png" alt="Júpiter" class="d-inline-block align-top" />
        </a>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav mr-auto">
                <li>@Html.ActionLink("Produtos", "Index", "Products", null, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Carrinho", "Index", "Cart", null, new { @class = "nav-link" })</li>
                <li>@Html.ActionLink("Histórico", "Index", "PurchaseHistory", null, new { @class = "nav-link" })</li>
                @if (User.IsInRole(RoleName.Admin))
                {
                    <li>@Html.ActionLink("Usuários", "Index", "UserManager", null, new { @class = "nav-link" })</li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>